### ISSUE TITLE
x cross slide questions

### ISSUE THREAD

**Issue by pantonvich** [kachurovskiy/megaels#1]
question on tables.html - and in general - on my x axis how do I account for the gear ratio from the x-stepper to cross slide screw pitch.
From your thingverse cross slide - it looks like you have a 3x - 54/18 but I'm not seeing that in the digital_feed_7e2 or tables.html code that you have posted. I have a 1mm cross slide but an odd 77/13. I started my els about a year ago and just started working on it again last month. I found your github in the last two weeks - so thanks for posting what you have. I'm not that good with github - so not sure how to correctly tag this

**Comment by gerritv** [comment]
You need to calculate the number of steps to revolve the leadscrew one revolution. The motor is usally 200 steps/rev, add in the 77/13 ratio (5.923) to get 1184.6 steps per rev?

**Comment by pantonvich** [comment]
thats what I was thinking so I tried setting MOTOR_X_STEP_PER_REV to 1185. I also tried setting the SCREW_X to 17 with motor 200 - but got an error - see below - looks like if I set the MxStep_X to 1 it's not an issue - so I'll try that.

Digital_Feed_7e2:55: error: static assertion failed: Ð?ÐµÐ²ÐµÑ€Ð½Ð¾ Ð·Ð°Ð´Ð°Ð½Ð¾ Ð·Ð½Ð°Ñ‡ÐµÐ½Ð¸Ðµ MAX_FEED
 static_assert(f > 1, "Ð?ÐµÐ²ÐµÑ€Ð½Ð¾ Ð·Ð°Ð´Ð°Ð½Ð¾ Ð·Ð½Ð°Ñ‡ÐµÐ½Ð¸Ðµ MAX_FEED");

**Comment by kachurovskiy** [comment]
I prefer changing the leadscrew pitch - using 1:3 reduction on cross-slide with 1.25mm screw I've entered 42 as SCREW_X. That gives something like 1% of error on cross-slide movements in theory but I'll think of something when it becomes a problem 😄 

Getting MAX_FEED error means that system wants you to reduce your MAX_FEED constant value (line 23). I believe validation errors like this ensure that the system has time to issue the stepper pulses in all conditions.

**Comment by kachurovskiy** [comment]
Another option to make MAX_FEED validation happy is to reduce micro-stepping e.g. from 800 steps per revolution to 400 - or so I believe.

**Comment by pantonvich** [comment]
I set it to 200 i.e 1 and and changed the driver to 200- I'm trying to verify what movement I get with 100 clicks from the handcoder ...

**Comment by pantonvich** [comment]
so with 
#define MOTOR_X_STEP_PER_REV 1185      // X motor steps (cross-slide) - almost always 200, microsteps configured below
#define SCREW_X              100 
#define McSTEP_X             1

I get 1mm on the x axis for 100 clicks of the hand coder - is that what I should expect?

**Comment by kachurovskiy** [comment]
> I get 1mm on the x axis for 100 clicks of the hand coder - is that what I should expect?

Yes. Or 10 clicks on 10x resolution.
