### ISSUE TITLE
Tachometer incorrect values

### ISSUE THREAD

**Issue by Shiftuia** [kachurovskiy/megaels#10]
If switch from tachometer to another mode and then switch mode back - values become incorrect.
Also it will be good to decrease refresh rate of tachometer values

https://user-images.githubusercontent.com/34735272/183307653-02c002ba-15f7-45f7-8428-4eee8d7d1a81.mov

.

**Comment by kachurovskiy** [comment]
@Shiftuia I believe that Alex in the video is using a different source code (zzzzzzz8989 as per https://youtu.be/AwgltElphHg?t=449), MegaEls doesn't even have an on-screen tachometer display AFAIK.

**Comment by Shiftuia** [comment]
It was first github repo on first of 3 google pages by request "Digital Feed 7e2". I thought, that maybe this repo is 'parent' of other versions. Someone from other versions developers could look here sometimes and see this issue. But I think, that unfortunately other versions are distributed on arduino forums or telegram channels.
You can close that issue if you think that it's non relevant

 Firmware name from video
<img width="384" alt="image" src="https://user-images.githubusercontent.com/34735272/183336026-ce01f817-fda9-46c7-b369-b12538a2c2f1.png">

**Comment by gerritv** [comment]
This version/variant says it has some tacho support: https://www.chipmaker.ru/files/file/17383/

AFAIK the only development is done via the chipmaker.ru site. Oleg A. is working on a new version but nothing beta released so far.

**Comment by Shiftuia** [comment]
Thank! I think it's better to close this issue. It may confuse some other developers.

P.S. still don't understand, why developer from chipmarket doesn't spare his files on any public git hosting...
