### ISSUE TITLE
Resistor arrays

### ISSUE THREAD

**Issue by tonywright** [kachurovskiy/megaels#13]
In the BOM you have "4 1kOhm resistor arrays with 9 resistors each" but the part that is linked: (https://www.aliexpress.com/item/32840103807.html) has 9 _PIN_ which is 8 resistors and a common isn't it? I hope the link is the correct one as this is what I have ordered :) Just checked and the circuit diagram has the 8 resistors and a common pin.

Tony

**Comment by kachurovskiy** [comment]
Good catch, fixed :)
