### ISSUE TITLE
Beeper

### ISSUE THREAD

**Issue by tonywright** [kachurovskiy/megaels#17]
I'm not getting any Beeps from the Megaels, I assumed that the beeper type is the sort that gives a constant beep sound while power is applied, not the sort that you need to modulate the power to get a frequency? It is polarised which I am sure I got the correct way round. Is there anything else I am missing? Did I assume wrong about the type of Beeper?

**Comment by kachurovskiy** [comment]
Tony, please post the picture of your beeper mounted on the PCB and link to the shop where you bought it. Thank you!

**Comment by tonywright** [comment]
Here is a pic and yes it is the wrong way round :)
All working now after I have swapped it round.
It was one of the buzzers supplied in one of the Arduino experiment packs of assorted devices. 
I hope it is reassuring to anyone else making one of these that all the problems I had (Not many really) were of my own making 

![20221007_131100](https://user-images.githubusercontent.com/17741253/194554664-6cdccf06-0c8a-4cdd-a86e-4cb14a37d16e.jpg)

**Comment by kachurovskiy** [comment]
Happy to hear it's resolved, thank you!
