### ISSUE TITLE
Réglage des paramètres 

### ISSUE THREAD

**Issue by Dididu12** [kachurovskiy/megaels#6]
I come to you because I want to know the different parameters that must be set in the code and what are the different settings for in the photo below. For example:  

SCREW_X (42) ??
MOTOR_X_STEP_PER_REV ??
REBOUND_X ??
REBOUND_Z ??

my turn and the same as kachurovskiy if I do the calculation of the x axis so 54/18= 3. (One complete engine revolution =200) So 3x200=600 MOTOR_X_STEP_PER_REV=600??

As soon as I change its parameters MAX_FEED starts to growl He and yet set to 20 

I hope here someone can help me thank you 
![Screenshot_20220222-093159_Chrome](https://user-images.githubusercontent.com/97460665/155094811-2ae84161-395b-457c-9c2e-3a4a8c4f01c2.jpg)

**Comment by pantonvich** [comment]
He adjusted screw_x. If you make rev =600 adjust screw_x to pitch of screw likely 1mm so set it to 100. Also you might need to set McSTEP_x to 1 - you will need to set the stepper driver to the same. If code still errors out adj the Max_Feed to a lower number. The point of the check is to not overwhelm the stepper motor with steps it can keep up with.

**Comment by kachurovskiy** [comment]
Dilan, what is your main and cross-slide leadscrew pitches? Mine are 2.0mm and 1.25mm. Knowing that and your 3:1 reduction on the cross-slide we should be able to tell you which values to put in the code and on stepper drivers. Thank you.

**Comment by Dididu12** [comment]
The main screw and 2mm and 1mm for cross carriage

**Comment by kachurovskiy** [comment]
Try the following:

```
#define MOTOR_Z_STEP_PER_REV 200      // Z motor steps (leadscrew) - almost always 200, microsteps configured below
#define SCREW_Z              200      // Z (leadscrew) pitch, in hundreds of a mm
#define McSTEP_Z             4        // Z driver microsteps (400 steps = 2, 800 steps = 4, etc)
#define MOTOR_X_STEP_PER_REV 200      // X motor steps (cross-slide) - almost always 200, microsteps configured below
#define SCREW_X              33       // 1.00mm via 3:1 reduction
#define REBOUND_X            200      // X backlash in microsteps
#define REBOUND_Z            200      // Z backlash in microsteps
#define McSTEP_X             2        // Z driver microsteps (400 steps = 2, 800 steps = 4, etc)
```

You would need to also set the main leadscrew driver to 800 steps and cross-slide driver to 400 steps and update tables via [tables.html](http://kachurovskiy.com/megaels/Digital_Feed_7e2/tables.html).

**Comment by Dididu12** [comment]
I'm trying this weekend thank you I'll keep you posted on the progress thank you 🤝👍🏼

**Comment by Dididu12** [comment]
![image](https://user-images.githubusercontent.com/97460665/155840327-b6c4890f-42f8-4b67-88e7-c5ee07bc16b0.png)
on the construction diagram I do not quite understand how the card is powered. I guess it's with the green terminals, which I can't translate well, the same for the pulse generator and the joystick, which wire goes where?? thank you very much for your help I soon finished assembling the map print

**Comment by kachurovskiy** [comment]
> MY QUESTION: CAN I LEAVE IT AS IS?? ITS INFLUENCE ON WHICH SETTING THANK YOU

I think yes for now.

> which wire goes where?

![image](https://user-images.githubusercontent.com/517919/155874617-43fa7a03-7ed8-40ae-b2e6-a2982de1fffc.png)

> pulse generator

Your pulse generator should have 4 terminals - 5V, ground, and 2 signal lines. Connect them correspondingly to 5V, ground and 2 remaining pins in the 5th terminal block (counting from the top).

> joystick

For the joystick that is recommended for the build, you need to connect together the wires so that clicking the joystick button or switching it in a given direction connects the corresponding pin on the 6th terminal block to the GND.

E.g. leaning joystick to the left should result in the following 2 pins getting connected:

![image](https://user-images.githubusercontent.com/517919/155874648-17b5ac8b-4ed7-4ff9-9f01-c69ebfcd2e18.png)

**Comment by Dididu12** [comment]
Thank you for your help I think I have understood everything now it's a great job again thank you

**Comment by Dididu12** [comment]
Hello everyone before assembling my print card I wanted to test the stop LEDs it turns out that there is one that does not light up the bottom one how to test it in operation with the m card

**Comment by Dididu12** [comment]
hello I have just tested the operation of the card it turns out that it does not work as expected I do not know why I have respected the connections well I hope to find a solution

**Comment by Dididu12** [comment]
https://user-images.githubusercontent.com/97460665/159134854-392a5770-ab21-449f-872d-c335e52fd27b.mp4

**Comment by Dididu12** [comment]
is there a way to weld the yellow resistors and the long black ones thank you

**Comment by kachurovskiy** [comment]
Dilan, can you please post the photos of your soldered PCB top and bottom sides? Some easy pitfalls:

- Soldering 10-leg resistors array wrong way
- Soldering LEDs wrong way

What about 8-position switches - do they work as intended? Also, brightness and feed potentiometers?

**Comment by Dididu12** [comment]
Je vous envoie la photo demain merci pour la réponse 👍🏼

**Comment by Dididu12** [comment]
There is not much that works the stops do not work the 8 position works when they want and the division mode is missing too

**Comment by Dididu12** [comment]
![20220227_193103](https://user-images.githubusercontent.com/97460665/159139247-d9dd79cb-808e-4ff9-8d6f-26aca4b29f73.jpg)
![20220227_193056](https://user-images.githubusercontent.com/97460665/159139257-85ea8d01-16bf-4e13-8c3c-4b560327068d.jpg)

**Comment by Dididu12** [comment]
![20220320_085516](https://user-images.githubusercontent.com/97460665/159153660-308e3817-1ac5-4bf4-a1f9-92b69cdb4f16.jpg)
![20220320_085612](https://user-images.githubusercontent.com/97460665/159153670-69251a44-5585-484e-bd4b-1098bae82630.jpg)
![20220320_085559](https://user-images.githubusercontent.com/97460665/159153679-d3b6e05c-c28a-4cdc-a19f-e42e329fe03c.jpg)
![20220320_085713](https://user-images.githubusercontent.com/97460665/159153724-a777f491-c066-444e-88a0-33308a3a2aed.jpg)
![20220320_085657](https://user-images.githubusercontent.com/97460665/159153734-bbec38bd-9ad2-4fa0-989b-1cb39edcf317.jpg)

the joystick button doesn't work

**Comment by kachurovskiy** [comment]
Dilan, looks like you've soldered the 9x resistor arrays the wrong way? IIRC the dot on the array should be over the square hole on the PCB. In other words, resistance between square hole and all other holes should be 1kOhm.

**Comment by Dididu12** [comment]
yes the problem was there but on the other hand the leds do not light up when you press the button any idea??

**Comment by kachurovskiy** [comment]
That is expected when the resistor array is connected incorrectly.

**Comment by Dididu12** [comment]
this also happens with array resistors in the right direction so it doesn't work yet??

**Comment by kachurovskiy** [comment]
Dilan, were you able to de-solder all 40 pins and swap the resistor arrays around? Can you post a photo of how it looks now? Many thanks.

**Comment by Dididu12** [comment]
ok I'm not at home my evenings I send you his thank you and yes I unsoldered and exchanged the black resistors

**Comment by Dididu12** [comment]
Everything seems to be back to normal, however the sphere mode does not work, that's normal

**Comment by Dididu12** [comment]
Hello I have just noticed that the stops are reversed especially the axes how to fix this thank you

**Comment by kachurovskiy** [comment]
Dilan, it sounds like you need to check the settings:

1. Go into the last mode (where the spindle angle is shown on screen) and rotate the spindle normally. Angle on screen should increment from 0 to 360 when you make a full turn of the spindle by hand.
2. Go into `Feed mm/min` mode, ensure both axes more in the correct direction. E.g. joystick right results in Z moving right. If not, adjust `Z_INVERT`.
3. Go into `Feed mm/min` mode, use the top-left knob set the speed to e.g. `50`, set joystick to right, use a ruler to ensure the carriage moves 50mm within 60 seconds. Same for X axis. If not, adjust parameters at the top of `Digital_Feed_7e2.ino` until it works.
4. Finally, re-calculate the tables using `tables.html`

**Comment by Dididu12** [comment]
ok I'll do it in the weekend I'll let you know

**Comment by Dididu12** [comment]
hello my problem and the following the x axis and reverse how to make it rotate in the right direction thank you

**Comment by Dididu12** [comment]
![Uploading 16482323569722772504916710016242.jpg…]()

**Comment by Dididu12** [comment]
![16482324344026884503455971020533](https://user-images.githubusercontent.com/97460665/160179150-9b09906a-2531-47e1-a6e0-51300fd083d7.jpg)

**Comment by Dididu12** [comment]
I just understood something I realize that as the x axis is inverted this is the problem that's why it doesn't take material it comes back much further each time

**Comment by kachurovskiy** [comment]
Dilan, I don't think there's a way to invert X at the moment in the code. Looks like so far no one needed that. Wonder if you happen to have a "reverse" switch on your stepper driver?

**Comment by Dididu12** [comment]
I just have the x axis which is reversed I don't know why the connections are well done what to do thank you

**Comment by gerritv** [comment]
you can reverse the direction of the motor by exchanging 2 wires, e.g. wires 1 and 2 coming out of the motor.

**Comment by Dididu12** [comment]
I tried reversing the wires, it didn't change anything.

**Comment by gerritv** [comment]
that is not possible. There are 2 coils in the motor, swapping the two wires for one coil reverses its direction.

**Comment by Dididu12** [comment]
ok but which one to exchange do you have a photo thank you

**Comment by gerritv** [comment]
This sketch shows wiring in the motor. You need a meter to determine the pairs. (don't worry about which is A or B.) Connect the pairs to controller. To reverse the motor
![IMG_20220327_074035](https://user-images.githubusercontent.com/8202594/160280099-984d66c7-2922-4a3d-a8e2-09e0ea997989.jpg)
 direction, swap A and A- wires, or B and B- wires.
![image](https://user-images.githubusercontent.com/8202594/160280061-9f1dd018-0e00-4957-821f-6eb2f564096c.png)

**Comment by Dididu12** [comment]
I changed the wiring and it still turns in the same direction, I find it weird?

**Comment by gerritv** [comment]
Can you post photo of your X motor and of the stepper driver? And mark what wires you changed?

**Comment by gerritv** [comment]
Lets verify the basics on your machine:
1. If you turn handwheel clockwise, the carriage should move toward spindle, Z axis. The cross slide should move toward back of lathe.
2. If you set LH limit, then move carriage to right and set RH limit, moving joy stick to left should move carriage toward spindle. (in Feed asynchronous mode, no need to have spindle turning)
3. In dividing mode, turn top of spinlde toward you, numbers should increase.

**Comment by Dididu12** [comment]
it is not possible to reverse the direction of rotation of the x axis with the Arduino code??

Otherwise yes you turn in the right direction with the joystick and the wheel

**Comment by gerritv** [comment]
When you cut threads, does the display say Ext or Int?

**Comment by Dididu12** [comment]
I'm waiting for the video to be put on youtube and I'll send you the link

The stopper of the x axis and in the wrong place let's admit when I want to put a stopper it is reversed only on the x axis

**Comment by gerritv** [comment]
for threading you don't set X limits, only Z

**Comment by Dididu12** [comment]
https://youtu.be/b2t2DgLo_qM

**Comment by Dididu12** [comment]
when I put the internal thread to make an external surface it works flawlessly, however when I put the button on external it gives me an internal thread so the tool moves away each time

**Comment by gerritv** [comment]
Well then that is your answer, the switch is wired backwards :-)

**Comment by Dididu12** [comment]
yes but when I wire the stopper in the right place and always in the wrong place

**Comment by gerritv** [comment]
Why change the code when the problem is elsewhere? The code works for the author and you are using his board.
If you wire the Ext/Int switch correctly, and the end stops are reversed, then are you certain the left/right limit switches are correct?
Do you have a voltmeter to test with?

**Comment by Dididu12** [comment]
yes I have voltmeter to test but I test or thank you very much

**Comment by Dididu12** [comment]
if I managed to change the direction of the motor, it would have solved the problem for a while Whatever I do, nothing changes by reversing the wires, I also find it weird

**Comment by Dididu12** [comment]
sayer I succeeded everything is working properly I am happy thank you to all those who help me for their trust 🥰😉

Just a quick question and is it possible to make a quarter round at the end of the room with the sphere function??
